/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trip;

import flugHopur.Flight;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import mock.HotelMock;
import mock.DayTourMock;
//import mock.FlightMock;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author M
 */
public class Window extends javax.swing.JFrame {

    BookingManager bookingManager = new BookingManager();
    FlightSearch flightSearch = new FlightSearch();
    FlightSearch flightSearchArr = new FlightSearch();
    HotelSearch hotelSearch = new HotelSearch();
    DayTourSearch dayTourSearch = new DayTourSearch();
    Validate validate = new Validate();
    BookingDatabase bookingDatabase = new BookingDatabase();
        
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compoundPainter1 = new org.jdesktop.swingx.painter.CompoundPainter();
        mainTabbedPane = new javax.swing.JTabbedPane();
        flightsPanel = new javax.swing.JPanel();
        bookButtonMessageLabel = new javax.swing.JLabel();
        jArrFlightMessageLabel = new javax.swing.JLabel();
        jDepFlightMessageLabel = new javax.swing.JLabel();
        numberOfTicketsComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fromFlightComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        toFlightComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        depFlightDatePicker = new org.jdesktop.swingx.JXDatePicker();
        arrFlightDatePicker = new org.jdesktop.swingx.JXDatePicker();
        oneWayCheckBox = new javax.swing.JCheckBox();
        flightSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdepFlightResultTable = new javax.swing.JTable();
        nextFromFlightButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jDepFlightTableScrollPane = new javax.swing.JScrollPane();
        jArrFlightResultTable = new javax.swing.JTable();
        jDepTableLabel = new javax.swing.JLabel();
        jArrTableLabel = new javax.swing.JLabel();
        bookFlightButton = new javax.swing.JButton();
        hotelsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        locationHotelComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        roomHotelComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        adultsHotelComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        childrenHotelComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        arrHotelDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel10 = new javax.swing.JLabel();
        depHotelDatePicker = new org.jdesktop.swingx.JXDatePicker();
        hotelSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hotelResultTable = new javax.swing.JTable();
        nextFromHotelButton = new javax.swing.JButton();
        bookHotelButton = new javax.swing.JButton();
        dayTourPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        areaTourComboBox = new javax.swing.JComboBox<>();
        ticketsTourComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dayTourSearchButton = new javax.swing.JButton();
        dayTourDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dayTourResultsTable = new javax.swing.JTable();
        nextFromDayTourButton = new javax.swing.JButton();
        typeTourComboBox = new javax.swing.JComboBox<>();
        languageCombobox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        pickupCheckBox = new javax.swing.JCheckBox();
        handicapCheckbox = new javax.swing.JCheckBox();
        bookTourButton = new javax.swing.JButton();
        customerPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        nextFromCustomerButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fieldForgotLabel = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        flightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookButtonMessageLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        bookButtonMessageLabel.setPreferredSize(new java.awt.Dimension(53, 16));
        flightsPanel.add(bookButtonMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 220, 30));

        jArrFlightMessageLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jArrFlightMessageLabel.setPreferredSize(new java.awt.Dimension(53, 16));
        flightsPanel.add(jArrFlightMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 600, -1));

        jDepFlightMessageLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jDepFlightMessageLabel.setPreferredSize(new java.awt.Dimension(53, 16));
        flightsPanel.add(jDepFlightMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 600, -1));

        numberOfTicketsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        numberOfTicketsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTicketsComboBoxActionPerformed(evt);
            }
        });
        flightsPanel.add(numberOfTicketsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, -1));

        jLabel1.setText("From");
        flightsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        fromFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akureyri", "Reykjavík", "Ísafjörður", "Eigilsstaðir" }));
        flightsPanel.add(fromFlightComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        jLabel2.setText("To");
        flightsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        toFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akureyri", "Reykjavík", "Ísafjörður", "Eigilsstaðir" }));
        flightsPanel.add(toFlightComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, -1));

        jLabel3.setText("Departure");
        flightsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Arrival");
        flightsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        depFlightDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depFlightDatePickerActionPerformed(evt);
            }
        });
        flightsPanel.add(depFlightDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        arrFlightDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrFlightDatePickerActionPerformed(evt);
            }
        });
        flightsPanel.add(arrFlightDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        oneWayCheckBox.setText("One Way");
        oneWayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayCheckBoxActionPerformed(evt);
            }
        });
        flightsPanel.add(oneWayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        flightSearchButton.setText("Search");
        flightSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightSearchButtonActionPerformed(evt);
            }
        });
        flightsPanel.add(flightSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jdepFlightResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Airline", "Departure", "Time", "Arrival", "Time", "Duration", "Ticket(s)", "Total Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jdepFlightResultTable);

        flightsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 670, 180));

        nextFromFlightButton.setText("Next >");
        nextFromFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFromFlightButtonActionPerformed(evt);
            }
        });
        flightsPanel.add(nextFromFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        jLabel16.setText("Number of tickets");
        flightsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jArrFlightResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Airline", "Departure", "Time", "Arrival", "Time", "Duration", "Ticket(s)", "Total Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDepFlightTableScrollPane.setViewportView(jArrFlightResultTable);

        flightsPanel.add(jDepFlightTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 670, 180));

        jDepTableLabel.setText("Departure:");
        flightsPanel.add(jDepTableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jArrTableLabel.setText("Arrival:");
        flightsPanel.add(jArrTableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        bookFlightButton.setText("Add to booking");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });
        flightsPanel.add(bookFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        mainTabbedPane.addTab("Flights", flightsPanel);

        hotelsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Location");
        hotelsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        locationHotelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akureyri", "Reykjavík" }));
        hotelsPanel.add(locationHotelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setText("Room");
        hotelsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        roomHotelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        roomHotelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomHotelComboBoxActionPerformed(evt);
            }
        });
        hotelsPanel.add(roomHotelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel7.setText("Adults");
        hotelsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        adultsHotelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        hotelsPanel.add(adultsHotelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel8.setText("Children");
        hotelsPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        childrenHotelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        hotelsPanel.add(childrenHotelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 70, -1));

        jLabel9.setText("Check in");
        hotelsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        hotelsPanel.add(arrHotelDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel10.setText("Check out");
        hotelsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        hotelsPanel.add(depHotelDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        hotelSearchButton.setText("Search");
        hotelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelSearchButtonActionPerformed(evt);
            }
        });
        hotelsPanel.add(hotelSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        hotelResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Hotel", "City", "Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(hotelResultTable);

        hotelsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 670, 350));

        nextFromHotelButton.setText("Next >");
        nextFromHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFromHotelButtonActionPerformed(evt);
            }
        });
        hotelsPanel.add(nextFromHotelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        bookHotelButton.setText("Add to booking");
        bookHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookHotelButtonActionPerformed(evt);
            }
        });
        hotelsPanel.add(bookHotelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        mainTabbedPane.addTab("Hotels", hotelsPanel);

        dayTourPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Area");
        dayTourPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        areaTourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Capital region", "East", "North", "South", "West" }));
        dayTourPanel.add(areaTourComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        ticketsTourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        dayTourPanel.add(ticketsTourComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel12.setText("Tickets");
        dayTourPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        dayTourSearchButton.setText("Search");
        dayTourSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTourSearchButtonActionPerformed(evt);
            }
        });
        dayTourPanel.add(dayTourSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));
        dayTourPanel.add(dayTourDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel14.setText("Date");
        dayTourPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel15.setText("Type");
        dayTourPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        dayTourResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Trip", "City", "Time", "Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dayTourResultsTable.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(dayTourResultsTable);

        dayTourPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 670, 350));

        nextFromDayTourButton.setText("Next >");
        nextFromDayTourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFromDayTourButtonActionPerformed(evt);
            }
        });
        dayTourPanel.add(nextFromDayTourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        typeTourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Adventure", "City walk", "Horse riding", "Hiking", "Sight seeing" }));
        dayTourPanel.add(typeTourComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, -1));

        languageCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Danish", "English", "German", "Icelandic", "Spanish", " ", " " }));
        dayTourPanel.add(languageCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel13.setText("Language");
        dayTourPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        pickupCheckBox.setText("Pickup");
        dayTourPanel.add(pickupCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        handicapCheckbox.setText("Handicap");
        dayTourPanel.add(handicapCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        bookTourButton.setText("Add to booking");
        bookTourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTourButtonActionPerformed(evt);
            }
        });
        dayTourPanel.add(bookTourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        mainTabbedPane.addTab("DayTours", dayTourPanel);

        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Name");
        customerPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        customerPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        jLabel18.setText("SSN");
        customerPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        customerPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        jLabel19.setText("Phone");
        customerPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        customerPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        nextFromCustomerButton.setText("Next >");
        nextFromCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFromCustomerButtonActionPerformed(evt);
            }
        });
        customerPanel.add(nextFromCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Invalid Name");
        customerPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("Invalid SSN");
        customerPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setText("Invalid Phone");
        customerPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        fieldForgotLabel.setForeground(new java.awt.Color(255, 0, 51));
        fieldForgotLabel.setText("Please fill out customer fields");
        customerPanel.add(fieldForgotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        mainTabbedPane.addTab("Customer", customerPanel);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        mainTabbedPane.addTab("Booking", bookPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightSearchButtonActionPerformed
        bookButtonMessageLabel.setText("");
        jDepFlightMessageLabel.setText("");
        jArrFlightMessageLabel.setText("");
        if(depFlightDatePicker.getDate() == null) {
            jDepFlightMessageLabel.setText("Choose date");
            return;     
        }
        if(arrFlightDatePicker.getDate() == null && !oneWayCheckBox.isSelected()) {
            jArrFlightMessageLabel.setText("Choose date or One Way");
            return;
        }
        ArrayList<Flight> results = flightSearch.search(depFlightDatePicker.getDate(), fromFlightComboBox.getSelectedItem().toString(), 
                toFlightComboBox.getSelectedItem().toString(), Integer.parseInt(numberOfTicketsComboBox.getItemAt(numberOfTicketsComboBox.getSelectedIndex())) );       
        
        if(results.get(0).getTotalPrice()!= 0) {
            createFlightTable(results, jdepFlightResultTable);
        }
        else jDepFlightMessageLabel.setText("No flights from "+ fromFlightComboBox.getSelectedItem()+
                " to "+ toFlightComboBox.getSelectedItem()+" on "+ depFlightDatePicker.getDate().toString().substring(0, 10)+" found");
      
        if (!oneWayCheckBox.isSelected() ){            
            ArrayList<Flight> resultsArr = flightSearchArr.search(arrFlightDatePicker.getDate(), toFlightComboBox.getSelectedItem().toString(), 
                    fromFlightComboBox.getSelectedItem().toString(), Integer.parseInt(numberOfTicketsComboBox.getItemAt(numberOfTicketsComboBox.getSelectedIndex())));
            
            if(resultsArr.get(0).getTotalPrice()!= 0) {
                createFlightTable(resultsArr, jArrFlightResultTable);
            }
            else jArrFlightMessageLabel.setText("No flights from "+ toFlightComboBox.getSelectedItem() +
                " to "+ fromFlightComboBox.getSelectedItem()+ " on "+ arrFlightDatePicker.getDate().toString().substring(0, 10)+" found");
        }
        
    }//GEN-LAST:event_flightSearchButtonActionPerformed

    private void oneWayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayCheckBoxActionPerformed
        oneWay();
    }//GEN-LAST:event_oneWayCheckBoxActionPerformed

    private void nextFromFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFromFlightButtonActionPerformed
        showPanel(hotelsPanel);
    }//GEN-LAST:event_nextFromFlightButtonActionPerformed

    private void hotelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelSearchButtonActionPerformed
        HotelMock[] results = hotelSearch.search(arrHotelDatePicker.getDate(), locationHotelComboBox.getSelectedItem().toString());
        createHotelTable(results);
    }//GEN-LAST:event_hotelSearchButtonActionPerformed

    private void nextFromHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFromHotelButtonActionPerformed
        showPanel(dayTourPanel);
    }//GEN-LAST:event_nextFromHotelButtonActionPerformed

    private void dayTourSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTourSearchButtonActionPerformed
        DayTourMock[] results = dayTourSearch.search(dayTourDatePicker.getDate(),areaTourComboBox.getSelectedItem().toString());
        createDayTourTable(results);
    }//GEN-LAST:event_dayTourSearchButtonActionPerformed

    private void nextFromDayTourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFromDayTourButtonActionPerformed
        showPanel(customerPanel);
    }//GEN-LAST:event_nextFromDayTourButtonActionPerformed

    private void roomHotelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomHotelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomHotelComboBoxActionPerformed

    private void numberOfTicketsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTicketsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfTicketsComboBoxActionPerformed

    private void depFlightDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depFlightDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depFlightDatePickerActionPerformed

    private void nextFromCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFromCustomerButtonActionPerformed
        addCustomer();
    }//GEN-LAST:event_nextFromCustomerButtonActionPerformed

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        if(mainTabbedPane.getSelectedIndex()==4)
            showBooking();
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addBookingToDatabase();
        updateFlightDatabase();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void arrFlightDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrFlightDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrFlightDatePickerActionPerformed

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        if (!oneWayCheckBox.isSelected()){
            if(!isRowSelected(jdepFlightResultTable) && !isRowSelected(jArrFlightResultTable)){
                bookButtonMessageLabel.setText("No flights selected");
                return;
            }           
            else if (!isRowSelected(jdepFlightResultTable)){
                bookButtonMessageLabel.setText("No departure flight selected");
            }            
            else if (!isRowSelected(jArrFlightResultTable)){
                bookButtonMessageLabel.setText("No arrival flight selected");
            }
            else if(isRowSelected(jdepFlightResultTable) && isRowSelected(jArrFlightResultTable)){
                bookButtonMessageLabel.setText("");
                addSelectedFlights(jdepFlightResultTable, flightSearch);
                addSelectedFlights(jArrFlightResultTable, flightSearchArr);
            }                     
        }
        
        if (oneWayCheckBox.isSelected()){
            if (isRowSelected(jdepFlightResultTable)){
                bookButtonMessageLabel.setText("");
                addSelectedFlights(jdepFlightResultTable, flightSearch);
            }
            else bookButtonMessageLabel.setText("No departure flight selected");
        }
    }//GEN-LAST:event_bookFlightButtonActionPerformed

    private void bookHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookHotelButtonActionPerformed
        addSelectedHotel();
    }//GEN-LAST:event_bookHotelButtonActionPerformed

    private void bookTourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTourButtonActionPerformed
        addSelectedDayTours();
    }//GEN-LAST:event_bookTourButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adultsHotelComboBox;
    private javax.swing.JComboBox<String> areaTourComboBox;
    private org.jdesktop.swingx.JXDatePicker arrFlightDatePicker;
    private org.jdesktop.swingx.JXDatePicker arrHotelDatePicker;
    private javax.swing.JLabel bookButtonMessageLabel;
    private javax.swing.JButton bookFlightButton;
    private javax.swing.JButton bookHotelButton;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton bookTourButton;
    private javax.swing.JComboBox<String> childrenHotelComboBox;
    private org.jdesktop.swingx.painter.CompoundPainter compoundPainter1;
    private javax.swing.JPanel customerPanel;
    private org.jdesktop.swingx.JXDatePicker dayTourDatePicker;
    private javax.swing.JPanel dayTourPanel;
    private javax.swing.JTable dayTourResultsTable;
    private javax.swing.JButton dayTourSearchButton;
    private org.jdesktop.swingx.JXDatePicker depFlightDatePicker;
    private org.jdesktop.swingx.JXDatePicker depHotelDatePicker;
    private javax.swing.JLabel fieldForgotLabel;
    private javax.swing.JButton flightSearchButton;
    private javax.swing.JPanel flightsPanel;
    private javax.swing.JComboBox<String> fromFlightComboBox;
    private javax.swing.JCheckBox handicapCheckbox;
    private javax.swing.JTable hotelResultTable;
    private javax.swing.JButton hotelSearchButton;
    private javax.swing.JPanel hotelsPanel;
    private javax.swing.JLabel jArrFlightMessageLabel;
    private javax.swing.JTable jArrFlightResultTable;
    private javax.swing.JLabel jArrTableLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jDepFlightMessageLabel;
    private javax.swing.JScrollPane jDepFlightTableScrollPane;
    private javax.swing.JLabel jDepTableLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jdepFlightResultTable;
    private javax.swing.JComboBox<String> languageCombobox;
    private javax.swing.JComboBox<String> locationHotelComboBox;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton nextFromCustomerButton;
    private javax.swing.JButton nextFromDayTourButton;
    private javax.swing.JButton nextFromFlightButton;
    private javax.swing.JButton nextFromHotelButton;
    private javax.swing.JComboBox<String> numberOfTicketsComboBox;
    private javax.swing.JCheckBox oneWayCheckBox;
    private javax.swing.JCheckBox pickupCheckBox;
    private javax.swing.JComboBox<String> roomHotelComboBox;
    private javax.swing.JComboBox<String> ticketsTourComboBox;
    private javax.swing.JComboBox<String> toFlightComboBox;
    private javax.swing.JComboBox<String> typeTourComboBox;
    // End of variables declaration//GEN-END:variables
    
    private void init() {
        jdepFlightResultTable.getColumnModel().getColumn(0).setMinWidth(0);
        jdepFlightResultTable.getColumnModel().getColumn(0).setMaxWidth(0);
        jArrFlightResultTable.getColumnModel().getColumn(0).setMinWidth(0);
        jArrFlightResultTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        hotelResultTable.getColumnModel().getColumn(0).setMinWidth(0);
        hotelResultTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        dayTourResultsTable.getColumnModel().getColumn(0).setMinWidth(0);
        dayTourResultsTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        depFlightDatePicker.setDate(new Date());
        arrFlightDatePicker.setDate(new Date());
        
        fromFlightComboBox.setSelectedIndex(1);
        
        mainTabbedPane.setEnabledAt(4, false);
        hideLabels();
        
    }
    
    private void createFlightTable(ArrayList<Flight> x, JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        if(x==null) return;
        
        for(int i=0; i<x.size(); i++){
            if(x.get(i)==null){return;}
            model.addRow(toObj(x.get(i),i));
        }
    }
    
    private void oneWay(){
        if(oneWayCheckBox.isSelected()){
            arrFlightDatePicker.setEnabled(false);
            
            jDepFlightTableScrollPane.setVisible(false);
            jArrTableLabel.setVisible(false);
            jArrFlightMessageLabel.setText("");
            
            
        }
        else{
            arrFlightDatePicker.setEnabled(true);
            jDepFlightTableScrollPane.setVisible(true);
            jArrTableLabel.setVisible(true);
        }
    }
    
    private boolean isRowSelected (JTable table){
        for (int i = 0; i < table.getRowCount(); i++) {
            boolean isChecked = (Boolean) table.getValueAt(i, 9);
            if (isChecked) return true;
        }
        return false;
    }
    
    private void addSelectedFlights(JTable table, FlightSearch s) {
        for (int i = 0; i < table.getRowCount(); i++) {
            boolean isChecked = (Boolean) table.getValueAt(i, 9);

            if (isChecked) {
                int index = (int) table.getValueAt(i, 0);
                Flight tmp = s.getFlight(index);
                bookingManager.addFlight(tmp);       
            }

        }
        mainTabbedPane.setEnabledAt(4, true);
    }
    
    private void showPanel(JPanel panel){
        mainTabbedPane.setSelectedComponent(panel);
    }
    
    private void createHotelTable(HotelMock[] x){
        DefaultTableModel model = (DefaultTableModel) hotelResultTable.getModel();
        model.setRowCount(0);
        if(x==null) return;
        
        for(int i=0; i<x.length; i++){
            if(x[i]==null){return;}
            model.addRow(hToObj(x[i],i));
        }
    }
    
    private void addSelectedHotel() {
        for (int i = 0; i < hotelResultTable.getRowCount(); i++) {
            boolean isChecked = (Boolean) hotelResultTable.getValueAt(i, 4);

            if (isChecked) {
                int index = (int) hotelResultTable.getValueAt(i, 0);
                HotelMock tmp = hotelSearch.getHotel(index);
                bookingManager.setHotel(tmp);
            }

        }
        mainTabbedPane.setEnabledAt(4, true);
    }
    
    private void createDayTourTable(DayTourMock[] x){
        DefaultTableModel model = (DefaultTableModel) dayTourResultsTable.getModel();
        model.setRowCount(0);
        if(x==null) return;
        
        for(int i=0; i<x.length; i++){
            if(x[i]==null){return;}
            model.addRow(dToObj(x[i],i));
        }
    }
    
    private void addSelectedDayTours() {
        for (int i = 0; i < dayTourResultsTable.getRowCount(); i++) {
            boolean isChecked = (Boolean) dayTourResultsTable.getValueAt(i, 5);

            if (isChecked) {
                int index = (int) dayTourResultsTable.getValueAt(i, 0);
                DayTourMock tmp = dayTourSearch.getDayTour(index);
                bookingManager.addDayTour(tmp);
            }

        }
        mainTabbedPane.setEnabledAt(4, true);
    }
    
    private void addCustomer(){
        String name = jTextField1.getText().trim();
        String ssn = jTextField2.getText().trim();
        String phone = jTextField3.getText().trim();
        if(!validateCustomer(name,ssn,phone)) return;
        
        bookingManager.updateCustomer(name, ssn, toInt(phone));
        showPanel(bookPanel);
    }
    
    private boolean validateCustomer(String name, String ssn, String phone){
        boolean b = true;
        hideLabels();
        if(!validate.name(name)){
            jLabel20.setVisible(true);
            b=false;
        }
        if(!validate.ssn(ssn)){
            jLabel21.setVisible(true);
            b=false;
        }
        if(!validate.phone(phone)){
            jLabel22.setVisible(true);
            b=false;
        }
        return b;
    }
    
    private void showBooking(){
        Booking booking = bookingManager.getBookings();
        
        String name = booking.customer.getName();
        String ssn = booking.customer.getSsn();
        int phone = booking.customer.getPhone();
        
        String s="";
        s+="Name: "+name+"\n"+"SSN: "+ssn+"\n"+"Phone: "+phone+"\n\n";
        
        ArrayList<Flight> fb = booking.flight;
        for(int i=0; i<fb.size(); i++){
            if(i==0){
                s+="Flights\n\n";
                s+="Airl\tFlight\tDepartur\tTime\tDate\tArrival\tTime\tDuration\tMax Luggage\tFood\tPassengers\tPrice\n";
                s+="----------\t-----------\t----------\t----------\t---------\t---------\t---------\t---------\t---------\t---------\t---------\t---------\n";
            }
            Flight y = fb.get(i);
            s+= y.getAirline()+"\t"+y.getFlightNumber()+"\t"+
                y.getDepartureLocation()+"\t"+y.getDepartureTime()+
                "\t "+y.getDepartureDate()+"\t"+y.getArrivalLocation()+
                "\t"+y.getArrivalTime()+"\t"+y.getDuration()+"\t"+
                y.getMaximumLuggageWeight()+"\t"+y.getFoodInfo()+
                "\t"+y.getNumberOfPassengers()+"\t"+y.getTotalPrice()+"\n";
        }
        
        HotelMock hb = booking.hotel;
        if(hb!=null){
            s+="\n\nHotel\n\n";
            s+="Name\tCity\tPrice\tDate\n";
            s+="----------\t-----------\t----------\t----------\n";
            s+=hb.name+"\t"+hb.city+"\t"+hb.price+"\t"+dts(hb.date);
        }
        
        ArrayList<DayTourMock> db = booking.daytour;
        for(int i=0; i<db.size(); i++){
            if(i==0){
                s+="\n\nDay Tours\n\n";
                s+="Name\tCity\tPrice\tTime\tDate\n";
                s+="----------\t-----------\t----------\t----------\t---------\n";
            }
            DayTourMock y = db.get(i);
            s+= y.trip+"\t"+y.city+"\t"+y.price+"\t"+y.time+"\t"+dts(y.date)+"\n";
        }
            
        
        jTextArea1.setText(s);
    }
    
    private void addBookingToDatabase(){
        Booking booking = bookingManager.getBookings();
        ArrayList<Flight> flights = booking.flight;
        HotelMock hotel = booking.hotel;
        ArrayList<DayTourMock> daytours = booking.daytour;
        
        if(booking.customer.getName() == "" || booking.customer.getSsn() == "" 
           || booking.customer.getPhone() == 0){
            fieldForgotLabel.setVisible(true);
            showPanel(customerPanel);
            return;
        }
        
        for(int i=0; i<flights.size(); i++){
            bookingDatabase.addBooking(booking.customer, "f", flights.get(i).getID());
        }
        
        if(hotel!=null)
            bookingDatabase.addBooking(booking.customer, "h", hotel.id);
        
        for(int i=0; i<daytours.size(); i++){
            bookingDatabase.addBooking(booking.customer, "d", daytours.get(i).id);
        }
        

    };
    /**
     * Responsible for updating databases of flight.
     */
    private void updateFlightDatabase(){
        Booking booking = bookingManager.getBookings();
        ArrayList<Flight> flights = booking.flight;
        for(int i=0; i<flights.size(); i++){
            flightSearch.updateDatabase(flights.get(i).getNumberOfPassengers(), 
                 flights.get(i).getTicketsAvailable(), flights.get(i).getID());
        }
    };

    
    private void hideLabels(){
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        fieldForgotLabel.setVisible(false);
    }
        
    //------------------- Hjálparföll ------------------------------
    private Object[] toObj(Flight x,int i){
        return new Object[]{i,x.getAirline(),x.getDepartureLocation(),x.getDepartureTime(),
                x.getArrivalLocation(),x.getArrivalTime(),x.getDuration(),x.getNumberOfPassengers(),x.getTotalPrice(),false};
    }
    
    private String brief(String x){
        if("Akureyri".equals(x))
            return "aey";
        else if("Reykjavík".equals(x))
            return "rvk";
        return "";
    }
    
    private Object[] hToObj(HotelMock x, int i){
        return new Object[]{i,x.name,x.city,x.price,false};
    }
    
    private Object[] dToObj(DayTourMock x, int i){
        return new Object[]{i,x.trip,x.city,x.time,x.price,false};
    }
    
    private void echo(Object o){
        System.out.println(o);
    }
    
    private int toInt(String s){
        return Integer.parseInt(s.replaceAll("[- ]", ""));
    }
    
    private String dts(Date d){
        DateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
        return formatter.format(d);
    }
    //----------------------------------------------------------------
    
    
}
